-- ============================================================
-- CORRECCIÓN DE VISTAS PARA EF CORE (TODAS LAS COLUMNAS)
-- ============================================================

USE InnovaTecBD;
GO

-- 1. VISTA PRODUCTOS
ALTER VIEW INV.V_PRODUCTOS_DETALLE AS
SELECT 
    P.*, -- Incluimos todas las columnas originales para mapeo EF Core
    C.NOMBRE AS CATEGORIA,
    (SELECT COUNT(*) FROM INV.EQUIPOS_IMEI WHERE ID_PRODUCTO = P.ID_PRODUCTO AND ESTADO_IMEI = 'DISPONIBLE') AS IMEIS_DISPONIBLES
FROM INV.PRODUCTOS P
LEFT JOIN INV.CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA;
GO

-- 2. VISTA HISTORIAL VENTAS
ALTER VIEW VEN.V_HISTORIAL_VENTAS AS
SELECT 
    V.*, -- Incluimos todas las columnas originales
    U.USERNAME AS CAJERO,
    COALESCE(P.NOMBRE_COMPLETO, 'CLIENTE GENERAL') AS CLIENTE,
    (V.TOTAL_NIO / V.TASA_CAMBIO_USD) AS TOTAL_USD
FROM VEN.VENTAS V
JOIN ADM.USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
LEFT JOIN ADM.PERSONAS P ON V.ID_PERSONA = P.ID_PERSONA;
GO

-- 3. VISTA TURNO ACTUAL
ALTER VIEW CAJA.V_ESTADO_TURNO_ACTUAL AS
SELECT 
    T.*, -- Incluimos todas las columnas originales
    U.USERNAME,
    (T.MONTO_INICIAL_NIO + T.TOTAL_EFECTIVO_NIO) AS SALDO_TEORICO_NIO,
    (T.MONTO_INICIAL_USD + T.TOTAL_EFECTIVO_USD) AS SALDO_TEORICO_USD
FROM CAJA.TURNOS T
JOIN ADM.USUARIOS U ON T.ID_USUARIO = U.ID_USUARIO
WHERE T.FECHA_CIERRE IS NULL;
GO

PRINT '>>> Vistas corregidas correctamente. <<<';
GO
