-- ============================================================
-- SCRIPT DE BASE DE DATOS: InnovaTec POS - Version Premium
-- Motor: SQL Server | Autenticacion: Windows Authentication
-- Autor: Antigravity | Fecha: 2026-04-09
-- ============================================================
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET CONCAT_NULL_YIELDS_NULL ON;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'InnovaTecBD')
    CREATE DATABASE InnovaTecBD;
GO

USE InnovaTecBD;
GO

-- ============================================================
-- 1. SCHEMAS
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAT')  EXEC('CREATE SCHEMA CAT');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ADM')  EXEC('CREATE SCHEMA ADM');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'INV')  EXEC('CREATE SCHEMA INV');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'VEN')  EXEC('CREATE SCHEMA VEN');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAJA') EXEC('CREATE SCHEMA CAJA');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'GAR')  EXEC('CREATE SCHEMA GAR');
GO

-- ============================================================
-- 2. CATALOGOS (CAT)
-- ============================================================

-- Estados generales reutilizables en todo el sistema
CREATE TABLE CAT.ESTADOS (
    ID_ESTADO   INT IDENTITY(1,1) CONSTRAINT PK_CAT_ESTADOS PRIMARY KEY,
    CODIGO      VARCHAR(30)  NOT NULL UNIQUE,   -- clave legible p.ej. 'ACTIVO'
    DESC_ESTADO VARCHAR(60)  NOT NULL,
    FECHA_CREACION DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO CAT.ESTADOS (CODIGO, DESC_ESTADO) VALUES
    ('ACTIVO',      'Activo'),
    ('INACTIVO',    'Inactivo'),
    ('ANULADO',     'Anulado'),
    ('EN_PROCESO',  'En Proceso'),
    ('FINALIZADO',  'Finalizado'),
    ('CANCELADO',   'Cancelado'),
    ('PENDIENTE',   'Pendiente'),
    ('VENCIDO',     'Vencido');
GO

-- Tipos de identificacion personal
CREATE TABLE CAT.TIPO_IDENTIFICACION (
    ID_TIPO  INT IDENTITY(1,1) CONSTRAINT PK_CAT_TIPO_ID PRIMARY KEY,
    DESC_TIPO VARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.TIPO_IDENTIFICACION (DESC_TIPO) VALUES
    ('CEDULA'), ('PASAPORTE'), ('RESIDENCIA');
GO

-- Generos
CREATE TABLE CAT.GENEROS (
    ID_GENERO   INT IDENTITY(1,1) CONSTRAINT PK_CAT_GENEROS PRIMARY KEY,
    DESC_GENERO VARCHAR(20)  NOT NULL,
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.GENEROS (DESC_GENERO) VALUES
    ('MASCULINO'), ('FEMENINO'), ('OTRO');
GO

-- Monedas
CREATE TABLE CAT.MONEDAS (
    ID_MONEDA INT IDENTITY(1,1) CONSTRAINT PK_CAT_MONEDAS PRIMARY KEY,
    CODIGO    VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE    VARCHAR(50) NOT NULL,
    SIMBOLO   VARCHAR(5)  NOT NULL,
    ES_BASE   BIT NOT NULL DEFAULT 0    -- 1 = moneda base del sistema (NIO)
);

INSERT INTO CAT.MONEDAS (CODIGO, NOMBRE, SIMBOLO, ES_BASE) VALUES
    ('NIO', 'Cordoba',  'C$', 1),
    ('USD', 'Dolar',    '$',  0);
GO

-- Metodos de pago
CREATE TABLE CAT.METODOS_PAGO (
    ID_METODO   INT IDENTITY(1,1) CONSTRAINT PK_CAT_METODOS_PAGO PRIMARY KEY,
    NOMBRE      VARCHAR(40) NOT NULL UNIQUE,    -- EFECTIVO_NIO, EFECTIVO_USD, TARJETA, TRANSFERENCIA
    AFECTA_CAJA BIT NOT NULL DEFAULT 1,         -- 0 = no afecta saldo fisico de caja
    ID_MONEDA   INT NULL,                       -- NULL = aplica a cualquiera
    FOREIGN KEY (ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);

INSERT INTO CAT.METODOS_PAGO (NOMBRE, AFECTA_CAJA, ID_MONEDA) VALUES
    ('EFECTIVO_NIO',    1, 1),   -- Efectivo en cordobas
    ('EFECTIVO_USD',    1, 2),   -- Efectivo en dolares (vuelto en NIO)
    ('TARJETA',         0, NULL),
    ('TRANSFERENCIA',   0, NULL);
GO

-- Periodos de garantia (1-12 meses, mas opciones especiales)
CREATE TABLE CAT.PERIODOS_GARANTIA (
    ID_PERIODO      INT IDENTITY(1,1) CONSTRAINT PK_CAT_GARANTIA PRIMARY KEY,
    DESCRIPCION     VARCHAR(30) NOT NULL,
    MESES           INT         NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.PERIODOS_GARANTIA (DESCRIPCION, MESES) VALUES
    ('SIN GARANTIA',  0),
    ('1 MES',         1),  ('2 MESES',   2),  ('3 MESES',   3),
    ('4 MESES',       4),  ('5 MESES',   5),  ('6 MESES',   6),
    ('7 MESES',       7),  ('8 MESES',   8),  ('9 MESES',   9),
    ('10 MESES',     10),  ('11 MESES', 11),  ('12 MESES', 12);
GO

-- Roles del sistema
CREATE TABLE CAT.ROLES (
    ID_ROL    INT IDENTITY(1,1) CONSTRAINT PK_CAT_ROLES PRIMARY KEY,
    NOMBRE    VARCHAR(50) NOT NULL UNIQUE,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.ROLES (NOMBRE) VALUES ('ADMINISTRADOR'), ('CAJERO');
GO

-- Modulos del sistema (para asignacion de permisos)
CREATE TABLE CAT.MODULOS (
    ID_MODULO   INT IDENTITY(1,1) CONSTRAINT PK_CAT_MODULOS PRIMARY KEY,
    NOMBRE      VARCHAR(100) NOT NULL UNIQUE,
    ICONO       VARCHAR(80)  NULL,     -- clase FontAwesome
    CONTROLLER  VARCHAR(100) NOT NULL,
    ORDEN       INT          NOT NULL DEFAULT 0,
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.MODULOS (NOMBRE, ICONO, CONTROLLER, ORDEN) VALUES
    ('Inventario',  'fa-boxes',         'Inventario',   1),
    ('Ventas',      'fa-cash-register', 'Ventas',       2),
    ('Caja',        'fa-vault',         'Caja',         3),
    ('Reportes',    'fa-chart-bar',     'Reportes',     4),
    ('Usuarios',    'fa-users-cog',     'Usuarios',     5),
    ('Configuracion','fa-cog',          'Configuracion',6);
GO

-- Tipos de movimiento de inventario
CREATE TABLE CAT.TIPO_MOVIMIENTO_INV (
    ID_TIPO  INT IDENTITY(1,1) CONSTRAINT PK_CAT_TIPO_MOV PRIMARY KEY,
    NOMBRE   VARCHAR(40) NOT NULL UNIQUE,   -- COMPRA, VENTA, DEVOLUCION, AJUSTE_ENTRADA, AJUSTE_SALIDA
    SIGNO    CHAR(1)     NOT NULL           -- '+' o '-'
        CONSTRAINT CHK_SIGNO CHECK (SIGNO IN ('+', '-'))
);

INSERT INTO CAT.TIPO_MOVIMIENTO_INV (NOMBRE, SIGNO) VALUES
    ('COMPRA',          '+'),
    ('VENTA',           '-'),
    ('DEVOLUCION',      '+'),
    ('AJUSTE_ENTRADA',  '+'),
    ('AJUSTE_SALIDA',   '-'),
    ('GARANTIA_SALIDA', '-'),
    ('GARANTIA_ENTRADA','+');
GO

-- ============================================================
-- 3. ADMINISTRACION (ADM)
-- ============================================================

-- Configuracion global del sistema
CREATE TABLE ADM.CONFIGURACION (
    ID_CONFIG           INT IDENTITY(1,1) CONSTRAINT PK_ADM_CONFIG PRIMARY KEY,
    CLAVE               NVARCHAR(80)  NOT NULL UNIQUE,
    VALOR               NVARCHAR(MAX) NOT NULL,
    DESCRIPCION         NVARCHAR(255) NULL,
    SOLO_ADMIN          BIT NOT NULL DEFAULT 1,
    ULTIMA_MODIFICACION DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MODIFICADO_POR      INT NULL    -- FK a ADM.USUARIOS (se agrega despues)
);

INSERT INTO ADM.CONFIGURACION (CLAVE, VALOR, DESCRIPCION, SOLO_ADMIN) VALUES
    ('Empresa_Nombre',          'InnovaTec POS', 'Nombre del negocio para recibos',       0),
    ('Empresa_RUC',             'J00000000000', 'RUC del negocio',                        0),
    ('Empresa_Telefono',        '+505 0000 0000', 'Teléfono de contacto',                  0),
    ('Empresa_Direccion',       'Managua, Nicaragua', 'Dirección física',                  0),
    ('Empresa_Logo',            'images/logo.png', 'Ruta al logo de la empresa',           0),
    ('Moneda_TasaCambio',       '36.50',        'Tasa de cambio Dolar a Cordoba',        1),
    ('Moneda_Principal',        '1',            'ID moneda base (NIO)',                  1),
    ('Hardware_Impresora',      '',             'Nombre impresora termica configurada',  0),
    ('STOCK_MINIMO_DEFAULT',    '5',            'Stock minimo por defecto al crear prod',1),
    ('PERMITE_VENTA_SIN_CAJA',  '0',            '1=Permite venta sin apertura de caja',  1);
GO

-- Personas (entidad base: clientes y empleados)
CREATE TABLE ADM.PERSONAS (
    ID_PERSONA          INT IDENTITY(1,1) CONSTRAINT PK_ADM_PERSONAS PRIMARY KEY,
    PRIMER_NOMBRE       VARCHAR(40) NOT NULL,
    SEGUNDO_NOMBRE      VARCHAR(40) NULL,
    PRIMER_APELLIDO     VARCHAR(40) NOT NULL,
    SEGUNDO_APELLIDO    VARCHAR(40) NULL,
    ID_TIPO_ID          INT NOT NULL,
    NUM_IDENTIFICACION  VARCHAR(25) NOT NULL,
    ID_GENERO           INT NULL,
    TELEFONO            VARCHAR(20) NULL,
    EMAIL               VARCHAR(100) NULL,
    DIRECCION           VARCHAR(250) NULL,
    ES_CLIENTE          BIT NOT NULL DEFAULT 1,
    ES_EMPLEADO         BIT NOT NULL DEFAULT 0,
    FECHA_CREACION      DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT UQ_PERSONA_IDENTIFICACION UNIQUE (ID_TIPO_ID, NUM_IDENTIFICACION),
    FOREIGN KEY (ID_TIPO_ID)  REFERENCES CAT.TIPO_IDENTIFICACION(ID_TIPO),
    FOREIGN KEY (ID_GENERO)   REFERENCES CAT.GENEROS(ID_GENERO),
    FOREIGN KEY (ID_ESTADO)   REFERENCES CAT.ESTADOS(ID_ESTADO)
);

-- Nombre completo calculado (no-persisted para evitar restriccion de QUOTED_IDENTIFIER)
ALTER TABLE ADM.PERSONAS
    ADD NOMBRE_COMPLETO AS (
        PRIMER_NOMBRE + ' ' +
        ISNULL(SEGUNDO_NOMBRE + ' ', '') +
        PRIMER_APELLIDO +
        ISNULL(' ' + SEGUNDO_APELLIDO, '')
    );
GO

-- Empleados
CREATE TABLE ADM.EMPLEADOS (
    ID_EMPLEADO         INT IDENTITY(1,1) CONSTRAINT PK_ADM_EMPLEADOS PRIMARY KEY,
    ID_PERSONA          INT NOT NULL,
    ID_ROL              INT NOT NULL,
    FECHA_CONTRATACION  DATE NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT UQ_EMPLEADO_PERSONA UNIQUE (ID_PERSONA),
    FOREIGN KEY (ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY (ID_ROL)     REFERENCES CAT.ROLES(ID_ROL),
    FOREIGN KEY (ID_ESTADO)  REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Usuarios del sistema
CREATE TABLE ADM.USUARIOS (
    ID_USUARIO      INT IDENTITY(1,1) CONSTRAINT PK_ADM_USUARIOS PRIMARY KEY,
    USERNAME        VARCHAR(80)  NOT NULL UNIQUE,   -- cedula del empleado
    PASSWORD_HASH   VARBINARY(64) NOT NULL,
    PASSWORD_SALT   VARBINARY(32) NOT NULL,
    ID_EMPLEADO     INT NOT NULL,
    ID_ROL          INT NOT NULL,
    FECHA_CREACION  DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ULTIMO_ACCESO   DATETIME2 NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES ADM.EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_ROL)      REFERENCES CAT.ROLES(ID_ROL),
    FOREIGN KEY (ID_ESTADO)   REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Agregar FK diferida a CONFIGURACION
ALTER TABLE ADM.CONFIGURACION
    ADD CONSTRAINT FK_CONFIG_USUARIO
    FOREIGN KEY (MODIFICADO_POR) REFERENCES ADM.USUARIOS(ID_USUARIO);
GO

-- Permisos de modulos por usuario
CREATE TABLE ADM.USUARIO_MODULOS (
    ID_USUARIO  INT NOT NULL,
    ID_MODULO   INT NOT NULL,
    CONSTRAINT PK_USUARIO_MODULOS PRIMARY KEY (ID_USUARIO, ID_MODULO),
    FOREIGN KEY (ID_USUARIO) REFERENCES ADM.USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_MODULO)  REFERENCES CAT.MODULOS(ID_MODULO)
);
GO

-- ============================================================
-- 4. INVENTARIO (INV)
-- ============================================================

-- Categorias de producto
CREATE TABLE INV.CATEGORIAS (
    ID_CATEGORIA    INT IDENTITY(1,1) CONSTRAINT PK_INV_CATEGORIAS PRIMARY KEY,
    NOMBRE          VARCHAR(80)  NOT NULL UNIQUE,
    DESCRIPCION     VARCHAR(200) NULL,
    MANEJA_IMEI     BIT NOT NULL DEFAULT 0,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO INV.CATEGORIAS (NOMBRE, MANEJA_IMEI) VALUES
    ('CELULARES', 1), ('ACCESORIOS', 0), ('ARTICULOS VARIOS', 0);
GO

-- Productos (maestro de inventario)
CREATE TABLE INV.PRODUCTOS (
    ID_PRODUCTO     INT IDENTITY(1,1) CONSTRAINT PK_INV_PRODUCTOS PRIMARY KEY,
    CODIGO_BARRAS   NVARCHAR(100) NULL,
    NOMBRE          NVARCHAR(150) NOT NULL,
    MARCA           NVARCHAR(100) NULL,
    MODELO          NVARCHAR(100) NULL,
    ALMACENAMIENTO  NVARCHAR(50)  NULL,   -- Solo telefonos (ej: 128GB)
    COLOR           NVARCHAR(50)  NULL,
    ID_CATEGORIA    INT           NULL,
    TIPO_PRODUCTO   VARCHAR(20)  NOT NULL DEFAULT 'ARTICULO'
        CONSTRAINT CHK_TIPO_PRODUCTO CHECK (TIPO_PRODUCTO IN ('TELEFONO','ARTICULO','ACCESORIO')),
    PRECIO_COMPRA   DECIMAL(12,2) NULL,        -- Costo (para reporte de ganancia)
    PRECIO_VENTA    DECIMAL(12,2) NOT NULL,
    STOCK_ACTUAL    INT  NOT NULL DEFAULT 0,
    STOCK_MINIMO    INT  NOT NULL DEFAULT 0, --Es editable por el usuario
    ACTIVO          BIT  NOT NULL DEFAULT 1,
    FECHA_CREACION  DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CREADO_POR      INT NULL,
    CONSTRAINT CHK_INV_STOCK_POSITIVO CHECK (STOCK_ACTUAL >= 0),
    CONSTRAINT CHK_INV_PRECIO_POSITIVO CHECK (PRECIO_VENTA > 0),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES INV.CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (CREADO_POR)   REFERENCES ADM.USUARIOS(ID_USUARIO)
);

-- Columna calculada para estado de stock (no-persisted)
ALTER TABLE INV.PRODUCTOS
    ADD ESTADO_STOCK AS (
        CASE
            WHEN STOCK_ACTUAL <= 0           THEN 'AGOTADO'
            WHEN STOCK_ACTUAL <= STOCK_MINIMO THEN 'CRITICO'
            ELSE 'DISPONIBLE'
        END
    );
GO

-- IMEIs individuales de telefonos en stock
CREATE TABLE INV.EQUIPOS_IMEI (
    ID_IMEI         INT IDENTITY(1,1) CONSTRAINT PK_INV_IMEI PRIMARY KEY,
    ID_PRODUCTO     INT NOT NULL,
    IMEI            NVARCHAR(20) NOT NULL CONSTRAINT UQ_INV_IMEI UNIQUE,
    ESTADO_IMEI     VARCHAR(20)  NOT NULL DEFAULT 'DISPONIBLE'
        CONSTRAINT CHK_ESTADO_IMEI CHECK (ESTADO_IMEI IN
            ('DISPONIBLE','VENDIDO','DEVUELTO','EN_GARANTIA','DANADO')),
    FECHA_INGRESO   DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    INGRESADO_POR   INT NULL,
    OBSERVACION     VARCHAR(200) NULL,
    FOREIGN KEY (ID_PRODUCTO)   REFERENCES INV.PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (INGRESADO_POR) REFERENCES ADM.USUARIOS(ID_USUARIO)
);
GO

-- Historial de movimientos de inventario (auditoria)
CREATE TABLE INV.MOVIMIENTOS (
    ID_MOVIMIENTO   INT IDENTITY(1,1) CONSTRAINT PK_INV_MOVIMIENTOS PRIMARY KEY,
    ID_PRODUCTO     INT  NOT NULL,
    ID_TIPO_MOV     INT  NOT NULL,
    CANTIDAD        INT  NOT NULL,
    STOCK_ANTES     INT  NOT NULL,
    STOCK_DESPUES   INT  NOT NULL,
    ID_REFERENCIA   INT  NULL,     -- ID de venta, garantia, etc.
    TABLA_REFERENCIA VARCHAR(50) NULL,  -- 'VEN.VENTAS', 'GAR.GARANTIAS', etc.
    OBSERVACION     VARCHAR(200) NULL,
    FECHA_MOV       DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    REGISTRADO_POR  INT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO)    REFERENCES INV.PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (ID_TIPO_MOV)    REFERENCES CAT.TIPO_MOVIMIENTO_INV(ID_TIPO),
    FOREIGN KEY (REGISTRADO_POR) REFERENCES ADM.USUARIOS(ID_USUARIO)
);
GO

-- TRIGGER PARA AUDITORIA AUTOMATICA DE STOCK
CREATE TRIGGER INV.Trg_Productos_Auditoria
ON INV.PRODUCTOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    
    -- Solo actuar si el stock actual cambió
    IF UPDATE(STOCK_ACTUAL)
    BEGIN
        INSERT INTO INV.MOVIMIENTOS (
            ID_PRODUCTO, ID_TIPO_MOV, CANTIDAD, STOCK_ANTES, 
            STOCK_DESPUES, OBSERVACION, REGISTRADO_POR, FECHA_MOV
        )
        SELECT 
            i.ID_PRODUCTO,
            (CASE 
                WHEN i.STOCK_ACTUAL > d.STOCK_ACTUAL THEN 4 -- AJUSTE_ENTRADA
                ELSE 5 -- AJUSTE_SALIDA
             END),
            ABS(i.STOCK_ACTUAL - d.STOCK_ACTUAL),
            d.STOCK_ACTUAL,
            i.STOCK_ACTUAL,
            ISNULL(CAST(SESSION_CONTEXT(N'Observacion') AS NVARCHAR(200)), 'Ajuste de sistema'),
            ISNULL(CAST(SESSION_CONTEXT(N'UsuarioId') AS INT), 1), -- Default a Admin si no hay sesión
            SYSDATETIME()
        FROM inserted i
        JOIN deleted d ON i.ID_PRODUCTO = d.ID_PRODUCTO
        WHERE i.STOCK_ACTUAL <> d.STOCK_ACTUAL;
    END
END;
GO

-- ============================================================
-- 5. CAJA (CAJA)
-- ============================================================

-- Denominaciones validas por moneda
CREATE TABLE CAJA.DENOMINACIONES (
    ID_DENOMINACION INT IDENTITY(1,1) CONSTRAINT PK_CAJA_DENOM PRIMARY KEY,
    ID_MONEDA       INT             NOT NULL,
    VALOR           DECIMAL(12,2)   NOT NULL,
    TIPO            VARCHAR(10)     NOT NULL  -- 'BILLETE' o 'MONEDA'
        CONSTRAINT CHK_TIPO_DENOM CHECK (TIPO IN ('BILLETE','MONEDA')),
    ORDEN           INT             NOT NULL DEFAULT 0,
    CONSTRAINT UQ_DENOM UNIQUE (ID_MONEDA, VALOR),
    FOREIGN KEY (ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);

-- NIO
INSERT INTO CAJA.DENOMINACIONES (ID_MONEDA, VALOR, TIPO, ORDEN) VALUES
    (1,   1.00, 'MONEDA',  1), (1,  5.00, 'MONEDA',  2),
    (1,  10.00, 'BILLETE', 3), (1, 20.00, 'BILLETE', 4),
    (1,  50.00, 'BILLETE', 5), (1,100.00, 'BILLETE', 6),
    (1, 200.00, 'BILLETE', 7), (1,500.00, 'BILLETE', 8),
    (1,1000.00, 'BILLETE', 9);
-- USD
INSERT INTO CAJA.DENOMINACIONES (ID_MONEDA, VALOR, TIPO, ORDEN) VALUES
    (2,  1.00, 'BILLETE', 1), (2,  2.00, 'BILLETE', 2),
    (2,  5.00, 'BILLETE', 3), (2, 10.00, 'BILLETE', 4),
    (2, 20.00, 'BILLETE', 5), (2, 50.00, 'BILLETE', 6),
    (2,100.00, 'BILLETE', 7);
GO

-- Turno / Sesion de caja (uno activo por usuario)
CREATE TABLE CAJA.TURNOS (
    ID_TURNO                INT IDENTITY(1,1) CONSTRAINT PK_CAJA_TURNOS PRIMARY KEY,
    ID_USUARIO              INT NOT NULL,
    FECHA_APERTURA          DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FECHA_CIERRE            DATETIME2 NULL,
    -- Montos apertura
    MONTO_INICIAL_NIO       DECIMAL(18,2) NOT NULL DEFAULT 0,
    MONTO_INICIAL_USD       DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- Totales calculados al cierre
    TOTAL_VENTAS_NIO        DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_VENTAS_USD        DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_EFECTIVO_NIO      DECIMAL(18,2) NOT NULL DEFAULT 0,   -- solo pagos en efectivo NIO
    TOTAL_EFECTIVO_USD      DECIMAL(18,2) NOT NULL DEFAULT 0,   -- solo pagos en efectivo USD
    TOTAL_TARJETA           DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_TRANSFERENCIA     DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- Conteo fisico al cierre
    MONTO_CONTADO_NIO       DECIMAL(18,2) NULL,
    MONTO_CONTADO_USD       DECIMAL(18,2) NULL,
    -- Diferencias
    DIFERENCIA_NIO          DECIMAL(18,2) NULL,
    DIFERENCIA_USD          DECIMAL(18,2) NULL,
    -- Calidad del cuadre
    ESTADO_CUADRE           VARCHAR(20)   NULL   -- 'EXACTO','SOBRANTE','FALTANTE'
        CONSTRAINT CHK_ESTADO_CUADRE CHECK (ESTADO_CUADRE IN ('EXACTO','SOBRANTE','FALTANTE',NULL)),
    OBSERVACIONES           NVARCHAR(500) NULL,
    ID_ESTADO               INT NOT NULL DEFAULT 1,   -- 1=ABIERTO, 2=CERRADO
    FOREIGN KEY (ID_USUARIO) REFERENCES ADM.USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_ESTADO)  REFERENCES CAT.ESTADOS(ID_ESTADO)
);

-- Solo un turno ABIERTO por usuario a la vez
CREATE UNIQUE INDEX UX_TURNO_ACTIVO
    ON CAJA.TURNOS(ID_USUARIO)
    WHERE ID_ESTADO = 1;
GO

-- Detalle del conteo de billetes (apertura y cierre)
-- NOTA: SUBTOTAL = CANTIDAD * DENOMINACION.VALOR  (calculado en app o via JOIN)
CREATE TABLE CAJA.CONTEO_DENOMINACIONES (
    ID_CONTEO       INT IDENTITY(1,1) CONSTRAINT PK_CAJA_CONTEO PRIMARY KEY,
    ID_TURNO        INT NOT NULL,
    TIPO_CONTEO     VARCHAR(10) NOT NULL   -- 'APERTURA' o 'CIERRE'
        CONSTRAINT CHK_TIPO_CONTEO CHECK (TIPO_CONTEO IN ('APERTURA','CIERRE')),
    ID_DENOMINACION INT NOT NULL,
    CANTIDAD        INT NOT NULL DEFAULT 0,
    -- SUBTOTAL se obtiene haciendo JOIN con CAJA.DENOMINACIONES.VALOR
    -- SQL Server no permite subconsultas en columnas calculadas
    FOREIGN KEY (ID_TURNO)        REFERENCES CAJA.TURNOS(ID_TURNO),
    FOREIGN KEY (ID_DENOMINACION) REFERENCES CAJA.DENOMINACIONES(ID_DENOMINACION)
);
GO

-- ============================================================
-- 6. VENTAS (VEN)
-- ============================================================

-- Encabezado de la venta
CREATE TABLE VEN.VENTAS (
    ID_VENTA            INT IDENTITY(1,1) CONSTRAINT PK_VEN_VENTAS PRIMARY KEY,
    NUMERO_FACTURA      AS ('FAC-' + RIGHT('000000' + CAST(ID_VENTA AS VARCHAR), 6)),
    ID_TURNO            INT NOT NULL,
    ID_USUARIO          INT NOT NULL,       -- cajero
    ID_PERSONA          INT NULL,           -- cliente (NULL = consumidor final)
    TASA_CAMBIO_USD     DECIMAL(18,6) NOT NULL,   -- tasa vigente al momento de la venta
    SUBTOTAL_NIO        DECIMAL(12,2) NOT NULL DEFAULT 0,
    DESCUENTO_NIO       DECIMAL(12,2) NOT NULL DEFAULT 0,
    TOTAL_NIO           DECIMAL(12,2) NOT NULL DEFAULT 0,
    OBSERVACION         VARCHAR(300)  NULL,
    FECHA_VENTA         DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ANULADA             BIT NOT NULL DEFAULT 0,
    ID_USUARIO_ANULA    INT NULL,
    FECHA_ANULACION     DATETIME2 NULL,
    MOTIVO_ANULACION    VARCHAR(200) NULL,
    FOREIGN KEY (ID_TURNO)          REFERENCES CAJA.TURNOS(ID_TURNO),
    FOREIGN KEY (ID_USUARIO)        REFERENCES ADM.USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PERSONA)        REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY (ID_USUARIO_ANULA)  REFERENCES ADM.USUARIOS(ID_USUARIO)
);
GO

-- Detalle de cada linea de la venta
CREATE TABLE VEN.VENTA_DETALLE (
    ID_DETALLE          INT IDENTITY(1,1) CONSTRAINT PK_VEN_DETALLE PRIMARY KEY,
    ID_VENTA            INT NOT NULL,
    ID_PRODUCTO         INT NOT NULL,
    DESCRIPCION_SNAP    NVARCHAR(200) NOT NULL,  -- snapshot del nombre al momento de venta
    CANTIDAD            INT          NOT NULL,
    PRECIO_UNITARIO_NIO DECIMAL(12,2) NOT NULL,
    DESCUENTO_LINEA_NIO DECIMAL(12,2) NOT NULL DEFAULT 0,
    SUBTOTAL_NIO        DECIMAL(12,2) NOT NULL,
    -- Garantia aplicada a este producto en esta venta
    ID_PERIODO_GARANTIA INT NULL,               -- NULL = sin garantia
    FECHA_VENCE_GARANTIA DATE NULL,             -- calculada al cerrar venta
    FOREIGN KEY (ID_VENTA)              REFERENCES VEN.VENTAS(ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO)           REFERENCES INV.PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (ID_PERIODO_GARANTIA)   REFERENCES CAT.PERIODOS_GARANTIA(ID_PERIODO)
);
GO

-- IMEIs utilizados en cada linea de detalle (solo telefonos)
CREATE TABLE VEN.VENTA_DETALLE_IMEI (
    ID              INT IDENTITY(1,1) CONSTRAINT PK_VEN_DET_IMEI PRIMARY KEY,
    ID_DETALLE      INT         NOT NULL,
    ID_EQUIPO_IMEI  INT         NOT NULL,   -- FK a INV.EQUIPOS_IMEI
    IMEI_SNAP       NVARCHAR(20) NOT NULL,  -- snapshot del IMEI
    FOREIGN KEY (ID_DETALLE)    REFERENCES VEN.VENTA_DETALLE(ID_DETALLE),
    FOREIGN KEY (ID_EQUIPO_IMEI) REFERENCES INV.EQUIPOS_IMEI(ID_IMEI),
    CONSTRAINT UQ_VENTA_IMEI UNIQUE (ID_EQUIPO_IMEI)  -- un IMEI no puede venderse dos veces
);
GO

-- Pagos de la venta (puede haber varios en diferentes metodos/monedas)
CREATE TABLE VEN.PAGOS (
    ID_PAGO             INT IDENTITY(1,1) CONSTRAINT PK_VEN_PAGOS PRIMARY KEY,
    ID_VENTA            INT NOT NULL,
    ID_METODO_PAGO      INT NOT NULL,
    MONTO_PAGADO        DECIMAL(12,2) NOT NULL,       -- en la moneda del metodo
    TASA_APLICADA       DECIMAL(18,6) NULL,           -- solo para USD
    MONTO_EN_NIO        DECIMAL(12,2) NOT NULL,       -- equivalente en cordobas
    MONTO_RECIBIDO      DECIMAL(12,2) NULL,           -- efectivo recibido
    VUELTO_NIO          DECIMAL(12,2) NULL DEFAULT 0, -- vuelto siempre en NIO
    COD_REFERENCIA      VARCHAR(100)  NULL,           -- codigo transferencia / tarjeta
    FECHA_PAGO          DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (ID_VENTA)          REFERENCES VEN.VENTAS(ID_VENTA),
    FOREIGN KEY (ID_METODO_PAGO)    REFERENCES CAT.METODOS_PAGO(ID_METODO)
);
GO

-- ============================================================
-- 7. GARANTIAS (GAR)
-- ============================================================
-- Registro de garantias activas y su ciclo de vida

CREATE TABLE GAR.GARANTIAS (
    ID_GARANTIA         INT IDENTITY(1,1) CONSTRAINT PK_GAR_GARANTIAS PRIMARY KEY,
    ID_DETALLE_VENTA    INT NOT NULL,         -- origina en VEN.VENTA_DETALLE
    ID_EQUIPO_IMEI      INT NULL,             -- IMEI del telefono (si aplica)
    ID_PERSONA          INT NOT NULL,         -- cliente dueno de la garantia
    ID_PRODUCTO         INT NOT NULL,
    MESES_GARANTIA      INT NOT NULL,
    FECHA_INICIO        DATE NOT NULL,
    FECHA_VENCIMIENTO   DATE NOT NULL,
    ESTADO_GARANTIA     VARCHAR(20) NOT NULL DEFAULT 'ACTIVA'
        CONSTRAINT CHK_GAR_ESTADO CHECK (ESTADO_GARANTIA IN
            ('ACTIVA','USADA','VENCIDA','CANCELADA')),
    FOREIGN KEY (ID_DETALLE_VENTA)  REFERENCES VEN.VENTA_DETALLE(ID_DETALLE),
    FOREIGN KEY (ID_EQUIPO_IMEI)    REFERENCES INV.EQUIPOS_IMEI(ID_IMEI),
    FOREIGN KEY (ID_PERSONA)        REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY (ID_PRODUCTO)       REFERENCES INV.PRODUCTOS(ID_PRODUCTO)
);
GO

-- Reclamos / uso de garantia
CREATE TABLE GAR.RECLAMOS_GARANTIA (
    ID_RECLAMO          INT IDENTITY(1,1) CONSTRAINT PK_GAR_RECLAMOS PRIMARY KEY,
    ID_GARANTIA         INT NOT NULL,
    FECHA_RECLAMO       DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DESCRIPCION_FALLA   NVARCHAR(500) NOT NULL,
    TIPO_RESOLUCION     VARCHAR(30) NULL
        CONSTRAINT CHK_TIPO_RESOLUCION CHECK (TIPO_RESOLUCION IN
            ('REPARACION','REEMPLAZO','DEVOLUCION_DINERO','SIN_COBERTURA', NULL)),
    PRODUCTO_REEMPLAZO_ID INT NULL,     -- si se cambia el equipo
    NUEVO_IMEI            NVARCHAR(20) NULL,
    FECHA_RESOLUCION    DATETIME2 NULL,
    NOTAS_TECNICO       NVARCHAR(500) NULL,
    ID_USUARIO          INT NOT NULL,   -- quien registro el reclamo
    ID_ESTADO           INT NOT NULL DEFAULT 4,  -- EN_PROCESO por default
    FOREIGN KEY (ID_GARANTIA)         REFERENCES GAR.GARANTIAS(ID_GARANTIA),
    FOREIGN KEY (PRODUCTO_REEMPLAZO_ID) REFERENCES INV.PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (ID_USUARIO)          REFERENCES ADM.USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_ESTADO)           REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- ============================================================
-- 8. VISTAS UTILES
-- ============================================================
GO
CREATE VIEW VEN.V_RESUMEN_VENTAS AS
SELECT
    V.ID_VENTA,
    V.NUMERO_FACTURA,
    V.FECHA_VENTA,
    P.NOMBRE_COMPLETO                   AS CLIENTE,
    U_EMP.NOMBRE_COMPLETO               AS CAJERO,
    V.SUBTOTAL_NIO,
    V.DESCUENTO_NIO,
    V.TOTAL_NIO,
    V.ANULADA,
    T.FECHA_APERTURA                    AS APERTURA_TURNO
FROM VEN.VENTAS        V
JOIN CAJA.TURNOS       T   ON T.ID_TURNO    = V.ID_TURNO
JOIN ADM.USUARIOS      U   ON U.ID_USUARIO  = V.ID_USUARIO
JOIN ADM.EMPLEADOS     E   ON E.ID_EMPLEADO = U.ID_EMPLEADO
JOIN ADM.PERSONAS      U_EMP ON U_EMP.ID_PERSONA = E.ID_PERSONA
LEFT JOIN ADM.PERSONAS P   ON P.ID_PERSONA  = V.ID_PERSONA;
GO

CREATE VIEW INV.V_STOCK_CRITICO AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE,
    P.MARCA,
    P.MODELO,
    P.STOCK_ACTUAL,
    P.STOCK_MINIMO,
    P.ESTADO_STOCK,
    C.NOMBRE AS CATEGORIA,
    (SELECT COUNT(1) FROM INV.EQUIPOS_IMEI I
     WHERE I.ID_PRODUCTO = P.ID_PRODUCTO AND I.ESTADO_IMEI = 'DISPONIBLE') AS IMEI_DISPONIBLES
FROM INV.PRODUCTOS P
JOIN INV.CATEGORIAS C ON C.ID_CATEGORIA = P.ID_CATEGORIA
WHERE P.ACTIVO = 1
  AND P.ESTADO_STOCK IN ('CRITICO','AGOTADO');
GO

CREATE VIEW GAR.V_GARANTIAS_ACTIVAS AS
SELECT
    G.ID_GARANTIA,
    G.FECHA_INICIO,
    G.FECHA_VENCIMIENTO,
    DATEDIFF(DAY, SYSDATETIME(), G.FECHA_VENCIMIENTO) AS DIAS_RESTANTES,
    G.MESES_GARANTIA,
    G.ESTADO_GARANTIA,
    PR.NOMBRE   AS PRODUCTO,
    PR.MODELO,
    EI.IMEI,
    PE.NOMBRE_COMPLETO AS CLIENTE,
    PE.TELEFONO
FROM GAR.GARANTIAS     G
JOIN INV.PRODUCTOS     PR ON PR.ID_PRODUCTO  = G.ID_PRODUCTO
JOIN ADM.PERSONAS      PE ON PE.ID_PERSONA   = G.ID_PERSONA
LEFT JOIN INV.EQUIPOS_IMEI EI ON EI.ID_IMEI  = G.ID_EQUIPO_IMEI
WHERE G.ESTADO_GARANTIA = 'ACTIVA';
GO

CREATE VIEW CAJA.V_RESUMEN_TURNOS AS
SELECT
    T.ID_TURNO,
    PE.NOMBRE_COMPLETO      AS CAJERO,
    T.FECHA_APERTURA,
    T.FECHA_CIERRE,
    T.MONTO_INICIAL_NIO,
    T.TOTAL_VENTAS_NIO,
    T.TOTAL_EFECTIVO_NIO,
    T.TOTAL_EFECTIVO_USD,
    T.MONTO_CONTADO_NIO,
    T.DIFERENCIA_NIO,
    T.ESTADO_CUADRE,
    E.CODIGO                AS ESTADO
FROM CAJA.TURNOS       T
JOIN ADM.USUARIOS      U   ON U.ID_USUARIO  = T.ID_USUARIO
JOIN ADM.EMPLEADOS     EM  ON EM.ID_EMPLEADO= U.ID_EMPLEADO
JOIN ADM.PERSONAS      PE  ON PE.ID_PERSONA = EM.ID_PERSONA
JOIN CAT.ESTADOS       E   ON E.ID_ESTADO   = T.ID_ESTADO;
GO

-- ============================================================
-- 9. INDICES DE RENDIMIENTO
-- ============================================================
CREATE INDEX IX_VENTAS_FECHA         ON VEN.VENTAS(FECHA_VENTA);
CREATE UNIQUE INDEX UX_PRODUCTO_CODIGO_BARRAS ON INV.PRODUCTOS(CODIGO_BARRAS) WHERE CODIGO_BARRAS IS NOT NULL;
CREATE INDEX IX_VENTAS_USUARIO       ON VEN.VENTAS(ID_USUARIO);
CREATE INDEX IX_VENTAS_PERSONA       ON VEN.VENTAS(ID_PERSONA);
CREATE INDEX IX_DET_VENTA_ID         ON VEN.VENTA_DETALLE(ID_VENTA);
CREATE INDEX IX_DET_IMEI_DETALLE     ON VEN.VENTA_DETALLE_IMEI(ID_DETALLE);
CREATE INDEX IX_IMEI_ESTADO          ON INV.EQUIPOS_IMEI(ESTADO_IMEI);
CREATE INDEX IX_IMEI_PRODUCTO        ON INV.EQUIPOS_IMEI(ID_PRODUCTO);
CREATE INDEX IX_GARANTIAS_ESTADO     ON GAR.GARANTIAS(ESTADO_GARANTIA);
CREATE INDEX IX_GARANTIAS_PERSONA    ON GAR.GARANTIAS(ID_PERSONA);
CREATE INDEX IX_MOV_PRODUCTO         ON INV.MOVIMIENTOS(ID_PRODUCTO);
CREATE INDEX IX_MOV_FECHA            ON INV.MOVIMIENTOS(FECHA_MOV);
CREATE INDEX IX_PAGOS_VENTA          ON VEN.PAGOS(ID_VENTA);
CREATE INDEX IX_TURNOS_USUARIO       ON CAJA.TURNOS(ID_USUARIO);
GO

-- ============================================================
-- 10. VISTAS Y PROCEDIMIENTOS COMPLEMENTARIOS (REFACTORIZACION)
-- ============================================================
GO

-- 10.1 SEGURIDAD
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ADM].[sp_IniciarSesion]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [ADM].[sp_IniciarSesion];
GO

CREATE PROCEDURE [ADM].[sp_IniciarSesion]
    @Username NVARCHAR(80),
    @Password NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    -- Normalizar el Username (quitar guiones y espacios)
    SET @Username = REPLACE(REPLACE(@Username, '-', ''), ' ', '');

    DECLARE @UserId INT, @StoredHash VARBINARY(64), @StoredSalt VARBINARY(32), @Estado INT;

    SELECT @UserId = ID_USUARIO, @StoredHash = PASSWORD_HASH, @StoredSalt = PASSWORD_SALT, @Estado = ID_ESTADO
    FROM ADM.USUARIOS WHERE USERNAME = @Username;

    IF @UserId IS NULL
    BEGIN
        SELECT 0 AS Success, 'la cedula no es correcta' AS Message, NULL AS UserId;
        RETURN;
    END

    IF @Estado <> 1
    BEGIN
        SELECT 0 AS Success, 'El usuario se encuentra inactivo' AS Message, NULL AS UserId;
        RETURN;
    END

    IF @StoredHash = HASHBYTES('SHA2_512', @Password + CAST(@StoredSalt AS NVARCHAR(MAX)))
    BEGIN
        UPDATE ADM.USUARIOS SET ULTIMO_ACCESO = SYSDATETIME() WHERE ID_USUARIO = @UserId;
        SELECT 1 AS Success, 'Acceso concedido' AS Message, @UserId AS UserId;
    END
    ELSE
        SELECT 0 AS Success, 'contraseña incorrecta' AS Message, NULL AS UserId;
END
GO

-- 10.2 INVENTARIO
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_PRODUCTOS_DETALLE' AND schema_id = SCHEMA_ID('INV'))
    DROP VIEW INV.V_PRODUCTOS_DETALLE;
GO

CREATE VIEW INV.V_PRODUCTOS_DETALLE AS
SELECT 
    P.*,
    C.NOMBRE AS NOMBRE_CATEGORIA,
    (SELECT COUNT(1) FROM INV.EQUIPOS_IMEI I WHERE I.ID_PRODUCTO = P.ID_PRODUCTO AND I.ESTADO_IMEI = 'DISPONIBLE') AS CANTIDAD_IMEI_DISP
FROM INV.PRODUCTOS P
LEFT JOIN INV.CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA;
GO

IF EXISTS (SELECT 1 FROM sys.procedures WHERE name = 'sp_ListarProductos' AND schema_id = SCHEMA_ID('INV'))
    DROP PROCEDURE INV.sp_ListarProductos;
GO

CREATE PROCEDURE INV.sp_ListarProductos
    @Busqueda NVARCHAR(100) = NULL,
    @IdCategoria INT = NULL,
    @IncluirInactivos BIT = 0
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM INV.V_PRODUCTOS_DETALLE
    WHERE (@IncluirInactivos = 1 OR ACTIVO = 1)
      AND (@IdCategoria IS NULL OR ID_CATEGORIA = @IdCategoria OR @IdCategoria = 0)
      AND (@Busqueda IS NULL OR @Busqueda = '' OR
           NOMBRE LIKE '%' + @Busqueda + '%' OR 
           CODIGO_BARRAS LIKE '%' + @Busqueda + '%' OR 
           MARCA LIKE '%' + @Busqueda + '%' OR 
           MODELO LIKE '%' + @Busqueda + '%')
    ORDER BY ID_PRODUCTO DESC;
END;
GO

IF EXISTS (SELECT 1 FROM sys.procedures WHERE name = 'sp_MantenerProducto' AND schema_id = SCHEMA_ID('INV'))
    DROP PROCEDURE INV.sp_MantenerProducto;
GO

CREATE PROCEDURE INV.sp_MantenerProducto
    @IdProducto INT = NULL,
    @CodigoBarras NVARCHAR(100) = NULL,
    @Nombre NVARCHAR(150),
    @Marca NVARCHAR(100) = NULL,
    @Modelo NVARCHAR(100) = NULL,
    @Almacenamiento NVARCHAR(50) = NULL,
    @Color NVARCHAR(50) = NULL,
    @IdCategoria INT = NULL,
    @PrecioCompra DECIMAL(12,2) = NULL,
    @PrecioVenta DECIMAL(12,2),
    @StockActual INT = 0,
    @StockMinimo INT = 0,
    @Activo BIT = 1,
    @UsuarioId INT = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    BEGIN TRANSACTION;
    SET @CodigoBarras = NULLIF(LTRIM(RTRIM(@CodigoBarras)), '');
    SET @Nombre = LTRIM(RTRIM(@Nombre));

    DECLARE @TipoProducto VARCHAR(20) = 'ARTICULO', @ManejaImei BIT = 0, @CatNombre NVARCHAR(100);
    SELECT @ManejaImei = MANEJA_IMEI, @CatNombre = NOMBRE FROM INV.CATEGORIAS WHERE ID_CATEGORIA = @IdCategoria;
    IF @ManejaImei = 1 SET @TipoProducto = 'TELEFONO';
    ELSE IF @CatNombre LIKE '%Accesorio%' SET @TipoProducto = 'ACCESORIO';

    IF @CodigoBarras IS NOT NULL AND EXISTS (SELECT 1 FROM INV.PRODUCTOS WHERE CODIGO_BARRAS = @CodigoBarras AND (@IdProducto IS NULL OR ID_PRODUCTO <> @IdProducto))
        THROW 50001, 'El código de barras ya pertenece a otro producto.', 1;

    IF @IdProducto IS NULL OR @IdProducto = 0
    BEGIN
        INSERT INTO INV.PRODUCTOS (CODIGO_BARRAS, NOMBRE, MARCA, MODELO, ALMACENAMIENTO, COLOR, ID_CATEGORIA, TIPO_PRODUCTO, PRECIO_COMPRA, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, ACTIVO, CREADO_POR)
        VALUES (@CodigoBarras, @Nombre, @Marca, @Modelo, @Almacenamiento, @Color, @IdCategoria, @TipoProducto, @PrecioCompra, @PrecioVenta, @StockActual, @StockMinimo, @Activo, @UsuarioId);
        SET @IdProducto = SCOPE_IDENTITY();
    END
    ELSE
    BEGIN
        UPDATE INV.PRODUCTOS SET CODIGO_BARRAS = @CodigoBarras, NOMBRE = @Nombre, MARCA = @Marca, MODELO = @Modelo, ALMACENAMIENTO = @Almacenamiento, COLOR = @Color, ID_CATEGORIA = @IdCategoria, TIPO_PRODUCTO = @TipoProducto, PRECIO_COMPRA = @PrecioCompra, PRECIO_VENTA = @PrecioVenta, STOCK_ACTUAL = @StockActual, STOCK_MINIMO = @StockMinimo, ACTIVO = @Activo
        WHERE ID_PRODUCTO = @IdProducto;
    END
    COMMIT TRANSACTION;
    SELECT * FROM INV.V_PRODUCTOS_DETALLE WHERE ID_PRODUCTO = @IdProducto;
END;
GO

-- 10.3 VENTAS
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_HISTORIAL_VENTAS' AND schema_id = SCHEMA_ID('VEN'))
    DROP VIEW VEN.V_HISTORIAL_VENTAS;
GO

CREATE VIEW VEN.V_HISTORIAL_VENTAS AS
SELECT 
    V.*,
    U.USERNAME AS CAJERO,
    COALESCE(P.NOMBRE_COMPLETO, 'CLIENTE GENERAL') AS CLIENTE,
    (V.TOTAL_NIO / V.TASA_CAMBIO_USD) AS TOTAL_USD
FROM VEN.VENTAS V
JOIN ADM.USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
LEFT JOIN ADM.PERSONAS P ON V.ID_PERSONA = P.ID_PERSONA;
GO

IF EXISTS (SELECT 1 FROM sys.procedures WHERE name = 'sp_ProcesarVenta' AND schema_id = SCHEMA_ID('VEN'))
    DROP PROCEDURE VEN.sp_ProcesarVenta;
GO

CREATE PROCEDURE VEN.sp_ProcesarVenta
    @IdUsuario INT,
    @IdPersona INT = NULL,
    @DescuentoNio DECIMAL(12,2) = 0,
    @TasaCambioUsd DECIMAL(12,4) = 36.60,
    @ItemsJson NVARCHAR(MAX),
    @PaymentsJson NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    DECLARE @IdTurno INT, @IdVenta INT, @FechaActual DATETIME = GETDATE();
    SELECT TOP 1 @IdTurno = ID_TURNO FROM CAJA.TURNOS WHERE ID_USUARIO = @IdUsuario AND FECHA_CIERRE IS NULL ORDER BY FECHA_APERTURA DESC;
    IF @IdTurno IS NULL THROW 50002, 'Debe abrir un turno de caja antes de facturar.', 1;

    BEGIN TRANSACTION;
    DECLARE @SubtotalNio DECIMAL(12,2);
    SELECT @SubtotalNio = SUM(CAST(JSON_VALUE(item.[value], '$.SubTotal') AS DECIMAL(12,2))) FROM OPENJSON(@ItemsJson) AS item;
    DECLARE @TotalVentaNio DECIMAL(12,2) = @SubtotalNio - @DescuentoNio;

    INSERT INTO VEN.VENTAS (ID_TURNO, ID_USUARIO, ID_PERSONA, FECHA_VENTA, TASA_CAMBIO_USD, SUBTOTAL_NIO, DESCUENTO_NIO, TOTAL_NIO, ANULADA)
    VALUES (@IdTurno, @IdUsuario, @IdPersona, @FechaActual, @TasaCambioUsd, @SubtotalNio, @DescuentoNio, @TotalVentaNio, 0);
    SET @IdVenta = SCOPE_IDENTITY();

    INSERT INTO VEN.PAGOS (ID_VENTA, ID_METODO_PAGO, MONTO_PAGADO, TASA_APLICADA, MONTO_EN_NIO, COD_REFERENCIA, FECHA_PAGO)
    SELECT @IdVenta, CAST(JSON_VALUE(p.[value], '$.IdMetodoPago') AS INT), CAST(JSON_VALUE(p.[value], '$.Monto') AS DECIMAL(12,2)), CAST(JSON_VALUE(p.[value], '$.TasaCambio') AS DECIMAL(12,4)), CAST(JSON_VALUE(p.[value], '$.MontoEnNio') AS DECIMAL(12,2)), JSON_VALUE(p.[value], '$.Referencia'), @FechaActual
    FROM OPENJSON(@PaymentsJson) AS p;

    UPDATE T SET 
        T.TOTAL_EFECTIVO_NIO += ISNULL((SELECT SUM(CAST(JSON_VALUE(pj.[value], '$.MontoEnNio') AS DECIMAL(12,2))) FROM OPENJSON(@PaymentsJson) pj JOIN CAT.METODOS_PAGO mp ON mp.ID_METODO = CAST(JSON_VALUE(pj.[value], '$.IdMetodoPago') AS INT) JOIN CAT.MONEDAS m ON m.ID_MONEDA = mp.ID_MONEDA WHERE mp.NOMBRE LIKE '%EFECTIVO%' AND m.CODIGO = 'NIO'), 0),
        T.TOTAL_EFECTIVO_USD += ISNULL((SELECT SUM(CAST(JSON_VALUE(pj.[value], '$.Monto') AS DECIMAL(12,2))) FROM OPENJSON(@PaymentsJson) pj JOIN CAT.METODOS_PAGO mp ON mp.ID_METODO = CAST(JSON_VALUE(pj.[value], '$.IdMetodoPago') AS INT) JOIN CAT.MONEDAS m ON m.ID_MONEDA = mp.ID_MONEDA WHERE mp.NOMBRE LIKE '%EFECTIVO%' AND m.CODIGO = 'USD'), 0),
        T.TOTAL_TARJETA += ISNULL((SELECT SUM(CAST(JSON_VALUE(pj.[value], '$.MontoEnNio') AS DECIMAL(12,2))) FROM OPENJSON(@PaymentsJson) pj JOIN CAT.METODOS_PAGO mp ON mp.ID_METODO = CAST(JSON_VALUE(pj.[value], '$.IdMetodoPago') AS INT) WHERE mp.NOMBRE LIKE '%TARJETA%'), 0),
        T.TOTAL_TRANSFERENCIA += ISNULL((SELECT SUM(CAST(JSON_VALUE(pj.[value], '$.MontoEnNio') AS DECIMAL(12,2))) FROM OPENJSON(@PaymentsJson) pj JOIN CAT.METODOS_PAGO mp ON mp.ID_METODO = CAST(JSON_VALUE(pj.[value], '$.IdMetodoPago') AS INT) WHERE mp.NOMBRE LIKE '%TRANSFERENCIA%'), 0),
        T.TOTAL_VENTAS_NIO += @TotalVentaNio,
        T.TOTAL_VENTAS_USD += (@TotalVentaNio / @TasaCambioUsd)
    FROM CAJA.TURNOS T WHERE T.ID_TURNO = @IdTurno;

    INSERT INTO VEN.VENTA_DETALLE (ID_VENTA, ID_PRODUCTO, DESCRIPCION_SNAP, CANTIDAD, PRECIO_UNITARIO_NIO, SUBTOTAL_NIO, ID_PERIODO_GARANTIA, FECHA_VENCE_GARANTIA)
    SELECT @IdVenta, CAST(JSON_VALUE(i.[value], '$.IdProducto') AS INT), JSON_VALUE(i.[value], '$.Description'), CAST(JSON_VALUE(i.[value], '$.Quantity') AS INT), CAST(JSON_VALUE(i.[value], '$.UnitPrice') AS DECIMAL(12,2)), CAST(JSON_VALUE(i.[value], '$.SubTotal') AS DECIMAL(12,2)), NULL, NULL
    FROM OPENJSON(@ItemsJson) AS i;

    COMMIT TRANSACTION;
    SELECT * FROM VEN.VENTAS WHERE ID_VENTA = @IdVenta;
END;
GO

-- 10.4 CAJA
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_ESTADO_TURNO_ACTUAL' AND schema_id = SCHEMA_ID('CAJA'))
    DROP VIEW CAJA.V_ESTADO_TURNO_ACTUAL;
GO

CREATE VIEW CAJA.V_ESTADO_TURNO_ACTUAL AS
SELECT 
    T.*,
    U.USERNAME,
    (T.MONTO_INICIAL_NIO + T.TOTAL_EFECTIVO_NIO) AS SALDO_TEORICO_NIO,
    (T.MONTO_INICIAL_USD + T.TOTAL_EFECTIVO_USD) AS SALDO_TEORICO_USD
FROM CAJA.TURNOS T
JOIN ADM.USUARIOS U ON T.ID_USUARIO = U.ID_USUARIO
WHERE T.FECHA_CIERRE IS NULL;
GO

IF EXISTS (SELECT 1 FROM sys.procedures WHERE name = 'sp_GestionarTurno' AND schema_id = SCHEMA_ID('CAJA'))
    DROP PROCEDURE CAJA.sp_GestionarTurno;
GO

CREATE PROCEDURE CAJA.sp_GestionarTurno
    @Accion VARCHAR(10),
    @IdUsuario INT,
    @IdTurno INT = NULL,
    @MontoInicialNio DECIMAL(12,2) = 0,
    @MontoInicialUsd DECIMAL(12,2) = 0,
    @MontoFinalNio DECIMAL(12,2) = 0,
    @MontoFinalUsd DECIMAL(12,2) = 0,
    @Observaciones NVARCHAR(MAX) = NULL,
    @ConteosJson NVARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    DECLARE @IdTurnoResult INT;
    BEGIN TRANSACTION;
    IF @Accion = 'ABRIR'
    BEGIN
        IF EXISTS (SELECT 1 FROM CAJA.TURNOS WHERE ID_USUARIO = @IdUsuario AND FECHA_CIERRE IS NULL)
            THROW 50005, 'El usuario ya tiene un turno de caja abierto.', 1;
        INSERT INTO CAJA.TURNOS (ID_USUARIO, FECHA_APERTURA, MONTO_INICIAL_NIO, MONTO_INICIAL_USD, TOTAL_VENTAS_NIO, TOTAL_VENTAS_USD, TOTAL_EFECTIVO_NIO, TOTAL_EFECTIVO_USD, TOTAL_TARJETA, TOTAL_TRANSFERENCIA, ID_ESTADO)
        VALUES (@IdUsuario, GETDATE(), @MontoInicialNio, @MontoInicialUsd, 0, 0, 0, 0, 0, 0, 1);
        SET @IdTurnoResult = SCOPE_IDENTITY();
    END
    ELSE IF @Accion = 'CERRAR'
    BEGIN
        IF @IdTurno IS NULL SELECT TOP 1 @IdTurno = ID_TURNO FROM CAJA.TURNOS WHERE ID_USUARIO = @IdUsuario AND FECHA_CIERRE IS NULL ORDER BY FECHA_APERTURA DESC;
        IF @IdTurno IS NULL THROW 50006, 'No se encontró un turno abierto para cerrar.', 1;
        UPDATE CAJA.TURNOS SET FECHA_CIERRE = GETDATE(), MONTO_CONTADO_NIO = @MontoFinalNio, MONTO_CONTADO_USD = @MontoFinalUsd, OBSERVACIONES = @Observaciones, ID_ESTADO = 2 WHERE ID_TURNO = @IdTurno;
        SET @IdTurnoResult = @IdTurno;
    END
    COMMIT TRANSACTION;
    SELECT * FROM CAJA.TURNOS WHERE ID_TURNO = @IdTurnoResult;
END;
GO

-- 10.5 DASHBOARD & ESTADISTICAS
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_CLIENTE_DASHBOARD_STATS' AND schema_id = SCHEMA_ID('ADM'))
    DROP VIEW ADM.V_CLIENTE_DASHBOARD_STATS;
GO

CREATE VIEW ADM.V_CLIENTE_DASHBOARD_STATS AS
SELECT 
    (SELECT COUNT(*) FROM ADM.PERSONAS WHERE ES_CLIENTE = 1 AND ID_ESTADO = 1) AS TotalClientes,
    (SELECT COUNT(*) FROM GAR.GARANTIAS WHERE ESTADO_GARANTIA = 'ACTIVA') AS TotalGarantiasActivas,
    (SELECT COUNT(DISTINCT ID_PERSONA) FROM VEN.VENTAS WHERE FECHA_VENTA >= DATEADD(DAY, -30, GETDATE())) AS ClientesConComprasRecientes;
GO

-- 10.6 VENTAS COMPLEMENTARIO
IF EXISTS (SELECT 1 FROM sys.procedures WHERE name = 'sp_ConsultarFacturas' AND schema_id = SCHEMA_ID('VEN'))
    DROP PROCEDURE VEN.sp_ConsultarFacturas;
GO

CREATE PROCEDURE VEN.sp_ConsultarFacturas
    @Busqueda NVARCHAR(100) = NULL,
    @FechaInicio DATETIME = NULL,
    @FechaFin DATETIME = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM VEN.V_RESUMEN_VENTAS
    WHERE (@FechaInicio IS NULL OR FECHA_VENTA >= @FechaInicio)
      AND (@FechaFin IS NULL OR FECHA_VENTA <= @FechaFin)
      AND (@Busqueda IS NULL OR @Busqueda = '' OR
           NUMERO_FACTURA LIKE '%' + @Busqueda + '%' OR
           CLIENTE LIKE '%' + @Busqueda + '%')
    ORDER BY FECHA_VENTA DESC;
END;
GO

PRINT '>>> InnovaTecBD actualizada con vistas y procedimientos complementarios. <<<';
GO
