-- ============================================================
-- SCRIPT DE INSERCIÓN DE DATOS INICIALES (LIMPIO PARA PRODUCCIÓN)
-- PROYECTO: InnovaTecPOS
-- ============================================================
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE InnovaTecBD;
GO

-- 1. USUARIO ADMINISTRADOR (NORMALIZADO)
DECLARE @CedulaAdmin NVARCHAR(80) = '6291906021000V'; -- Sin guiones
DECLARE @PasswordAdmin NVARCHAR(MAX) = 'Polanco19';
DECLARE @PersonaID INT, @EmpleadoID INT, @UsuarioID INT;
DECLARE @Salt VARBINARY(32) = CRYPT_GEN_RANDOM(32);

-- A. Persona
IF NOT EXISTS (SELECT 1 FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.PERSONAS (PRIMER_NOMBRE, PRIMER_APELLIDO, ID_TIPO_ID, NUM_IDENTIFICACION, ID_GENERO, ES_CLIENTE, ES_EMPLEADO)
    VALUES ('Admin', 'InnovaTec', 1, @CedulaAdmin, 1, 0, 1);
    SET @PersonaID = SCOPE_IDENTITY();
END
ELSE SELECT @PersonaID = ID_PERSONA FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin;

-- B. Empleado
IF NOT EXISTS (SELECT 1 FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID)
BEGIN
    INSERT INTO ADM.EMPLEADOS (ID_PERSONA, ID_ROL, FECHA_CONTRATACION)
    VALUES (@PersonaID, 1, GETDATE());
    SET @EmpleadoID = SCOPE_IDENTITY();
END
ELSE SELECT @EmpleadoID = ID_EMPLEADO FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID;

-- C. Usuario
IF NOT EXISTS (SELECT 1 FROM ADM.USUARIOS WHERE USERNAME = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.USUARIOS (USERNAME, PASSWORD_HASH, PASSWORD_SALT, ID_EMPLEADO, ID_ROL)
    VALUES (@CedulaAdmin, HASHBYTES('SHA2_512', @PasswordAdmin + CAST(@Salt AS NVARCHAR(MAX))), @Salt, @EmpleadoID, 1);
    SET @UsuarioID = SCOPE_IDENTITY();

    -- ASIGNAR TODOS LOS MÓDULOS AL ADMIN
    INSERT INTO ADM.USUARIO_MODULOS (ID_USUARIO, ID_MODULO)
    SELECT @UsuarioID, ID_MODULO FROM CAT.MODULOS;
END
GO

PRINT '>>> Seed de datos completado (Admin creado exitosamente). <<<';
GO
