-- ============================================================
-- SCRIPT DE INSERCIÓN DE DATOS (DATA SEEDING) - VERSION NORMALIZADA
-- PROYECTO: InnovaTecPOS
-- FECHA: 2026-05-05
-- ============================================================
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE InnovaTecBD;
GO

-- 1. USUARIO ADMINISTRADOR (NORMALIZADO)
DECLARE @CedulaAdmin NVARCHAR(80) = '0010000000000U'; -- Sin guiones
DECLARE @PasswordAdmin NVARCHAR(MAX) = 'Admin123';
DECLARE @PersonaID INT, @EmpleadoID INT, @UsuarioID INT;
DECLARE @Salt VARBINARY(32) = CRYPT_GEN_RANDOM(32);

-- A. Persona
IF NOT EXISTS (SELECT 1 FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.PERSONAS (PRIMER_NOMBRE, PRIMER_APELLIDO, ID_TIPO_ID, NUM_IDENTIFICACION, ID_GENERO, ES_CLIENTE, ES_EMPLEADO)
    VALUES ('Admin', 'InnovaTec', 1, @CedulaAdmin, 1, 0, 1);
    SET @PersonaID = SCOPE_IDENTITY();
END
ELSE SELECT @PersonaID = ID_PERSONA FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin;

-- B. Empleado
IF NOT EXISTS (SELECT 1 FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID)
BEGIN
    INSERT INTO ADM.EMPLEADOS (ID_PERSONA, ID_ROL, FECHA_CONTRATACION)
    VALUES (@PersonaID, 1, GETDATE());
    SET @EmpleadoID = SCOPE_IDENTITY();
END
ELSE SELECT @EmpleadoID = ID_EMPLEADO FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID;

-- C. Usuario
IF NOT EXISTS (SELECT 1 FROM ADM.USUARIOS WHERE USERNAME = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.USUARIOS (USERNAME, PASSWORD_HASH, PASSWORD_SALT, ID_EMPLEADO, ID_ROL)
    VALUES (@CedulaAdmin, HASHBYTES('SHA2_512', @PasswordAdmin + CAST(@Salt AS NVARCHAR(MAX))), @Salt, @EmpleadoID, 1);
    SET @UsuarioID = SCOPE_IDENTITY();

    -- ASIGNAR TODOS LOS MÓDULOS AL ADMIN
    INSERT INTO ADM.USUARIO_MODULOS (ID_USUARIO, ID_MODULO)
    SELECT @UsuarioID, ID_MODULO FROM CAT.MODULOS;
END
GO

-- 2. PRODUCTOS DE PRUEBA
DECLARE @UsuarioID INT = (SELECT ID_USUARIO FROM ADM.USUARIOS WHERE USERNAME = '0010000000000U');
DECLARE @CatCelular INT = (SELECT ID_CATEGORIA FROM INV.CATEGORIAS WHERE NOMBRE = 'CELULARES');

IF @CatCelular IS NOT NULL AND NOT EXISTS (SELECT 1 FROM INV.PRODUCTOS WHERE NOMBRE = 'iPhone 15 Pro')
BEGIN
    INSERT INTO INV.PRODUCTOS (NOMBRE, MARCA, MODELO, ID_CATEGORIA, TIPO_PRODUCTO, PRECIO_COMPRA, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, ACTIVO, CREADO_POR)
    VALUES ('iPhone 15 Pro', 'Apple', '15 Pro', @CatCelular, 'TELEFONO', 850.00, 1099.00, 3, 1, 1, @UsuarioID);
    
    DECLARE @ProdID INT = SCOPE_IDENTITY();
    INSERT INTO INV.EQUIPOS_IMEI (ID_PRODUCTO, IMEI, ESTADO_IMEI, INGRESADO_POR) 
    VALUES (@ProdID, '350000000000001', 'DISPONIBLE', @UsuarioID),
           (@ProdID, '350000000000002', 'DISPONIBLE', @UsuarioID),
           (@ProdID, '350000000000003', 'DISPONIBLE', @UsuarioID);
END
GO

PRINT '>>> Seed de datos completado (Admin normalizado y Módulos asignados). <<<';
GO

