-- ============================================================
-- SCRIPT DE INSERCIÓN DE DATOS (DATA SEEDING)
-- PROYECTO: InnovaTecPOS
-- FECHA: 2026-04-10
-- ============================================================

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE InnovaTecBD;
GO

-- ============================================================
-- 1. USUARIO ADMINISTRADOR CON TODOS LOS PERMISOS
-- ============================================================

DECLARE @CedulaAdmin NVARCHAR(80) = '001-000000-0000U';
DECLARE @PasswordAdmin NVARCHAR(MAX) = 'Admin123';
DECLARE @PersonaID INT;
DECLARE @EmpleadoID INT;
DECLARE @UsuarioID INT;
DECLARE @Salt VARBINARY(32) = CRYPT_GEN_RANDOM(32);

-- A. Insertar Persona (Adm. del Sistema)
IF NOT EXISTS (SELECT 1 FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.PERSONAS (PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, ID_TIPO_ID, NUM_IDENTIFICACION, ID_GENERO, TELEFONO, EMAIL, DIRECCION, ES_CLIENTE, ES_EMPLEADO)
    VALUES ('Admin', 'General', 'InnovaTec', 'POS', 1, @CedulaAdmin, 1, '8888-8888', 'admin@innovatec.pos', 'Managua, Nicaragua', 0, 1);
    SET @PersonaID = SCOPE_IDENTITY();
END
ELSE
BEGIN
    SELECT @PersonaID = ID_PERSONA FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @CedulaAdmin;
END

-- B. Insertar Empleado (Rol Administrador = 1)
IF NOT EXISTS (SELECT 1 FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID)
BEGIN
    INSERT INTO ADM.EMPLEADOS (ID_PERSONA, ID_ROL, FECHA_CONTRATACION)
    VALUES (@PersonaID, 1, GETDATE());
    SET @EmpleadoID = SCOPE_IDENTITY();
END
ELSE
BEGIN
    SELECT @EmpleadoID = ID_EMPLEADO FROM ADM.EMPLEADOS WHERE ID_PERSONA = @PersonaID;
END

-- C. Insertar Usuario
IF NOT EXISTS (SELECT 1 FROM ADM.USUARIOS WHERE USERNAME = @CedulaAdmin)
BEGIN
    INSERT INTO ADM.USUARIOS (USERNAME, PASSWORD_HASH, PASSWORD_SALT, ID_EMPLEADO, ID_ROL)
    VALUES (@CedulaAdmin, HASHBYTES('SHA2_512', @PasswordAdmin + CAST(@Salt AS NVARCHAR(MAX))), @Salt, @EmpleadoID, 1);
    SET @UsuarioID = SCOPE_IDENTITY();
END
ELSE
BEGIN
    SELECT @UsuarioID = ID_USUARIO FROM ADM.USUARIOS WHERE USERNAME = @CedulaAdmin;
    -- Opcional: Actualizar password si se desea forzar
    UPDATE ADM.USUARIOS 
    SET PASSWORD_HASH = HASHBYTES('SHA2_512', @PasswordAdmin + CAST(@Salt AS NVARCHAR(MAX))),
        PASSWORD_SALT = @Salt
    WHERE ID_USUARIO = @UsuarioID;
END

-- ============================================================
-- 2. CATEGORIAS DE PRODUCTOS
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM INV.CATEGORIAS WHERE NOMBRE = 'Celulares')
    INSERT INTO INV.CATEGORIAS (NOMBRE, DESCRIPCION, ID_ESTADO) VALUES ('Celulares', 'Telefonos moviles y tablets', 1);

IF NOT EXISTS (SELECT 1 FROM INV.CATEGORIAS WHERE NOMBRE = 'Accesorios')
    INSERT INTO INV.CATEGORIAS (NOMBRE, DESCRIPCION, ID_ESTADO) VALUES ('Accesorios', 'Cargadores, fundas, etc.', 1);

DECLARE @CatCelular INT = (SELECT ID_CATEGORIA FROM INV.CATEGORIAS WHERE NOMBRE = 'Celulares');
DECLARE @CatAccesorio INT = (SELECT ID_CATEGORIA FROM INV.CATEGORIAS WHERE NOMBRE = 'Accesorios');

-- ============================================================
-- 3. PRODUCTOS DE PRUEBA
-- ============================================================

-- A. iPhone 15 Pro Max
IF NOT EXISTS (SELECT 1 FROM INV.PRODUCTOS WHERE CODIGO_BARRAS = '7501052148963')
BEGIN
    INSERT INTO INV.PRODUCTOS (NOMBRE, MARCA, MODELO, ALMACENAMIENTO, COLOR, ID_CATEGORIA, TIPO_PRODUCTO, PRECIO_COMPRA, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, CREADO_POR, CODIGO_BARRAS)
    VALUES ('iPhone 15 Pro Max', 'Apple', '15 Pro Max', '256GB', 'Titanio Natural', @CatCelular, 'TELEFONO', 950.00, 1199.00, 5, 2, @UsuarioID, '7501052148963');
    
    DECLARE @ProdIphone INT = SCOPE_IDENTITY();
    
    -- Insertar IMEIs para el stock actual
    INSERT INTO INV.EQUIPOS_IMEI (ID_PRODUCTO, IMEI, ESTADO_IMEI, INGRESADO_POR) VALUES 
    (@ProdIphone, '351234567890123', 'DISPONIBLE', @UsuarioID),
    (@ProdIphone, '351234567890124', 'DISPONIBLE', @UsuarioID),
    (@ProdIphone, '351234567890125', 'DISPONIBLE', @UsuarioID),
    (@ProdIphone, '351234567890126', 'DISPONIBLE', @UsuarioID),
    (@ProdIphone, '351234567890127', 'DISPONIBLE', @UsuarioID);
END

-- B. Funda MagSafe
IF NOT EXISTS (SELECT 1 FROM INV.PRODUCTOS WHERE CODIGO_BARRAS = '1092837465012')
BEGIN
    INSERT INTO INV.PRODUCTOS (NOMBRE, MARCA, MODELO, COLOR, ID_CATEGORIA, TIPO_PRODUCTO, PRECIO_COMPRA, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, CREADO_POR, CODIGO_BARRAS)
    VALUES ('Funda MagSafe Transparente', 'Apple', 'iPhone 15 Series', 'Transparente', @CatAccesorio, 'ARTICULO', 20.00, 49.00, 20, 5, @UsuarioID, '1092837465012');
END

-- C. Adaptador USB-C 20W
IF NOT EXISTS (SELECT 1 FROM INV.PRODUCTOS WHERE CODIGO_BARRAS = '4005808810214')
BEGIN
    INSERT INTO INV.PRODUCTOS (NOMBRE, MARCA, MODELO, ID_CATEGORIA, TIPO_PRODUCTO, PRECIO_COMPRA, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, CREADO_POR, CODIGO_BARRAS)
    VALUES ('Adaptador Corriente USB-C 20W', 'Apple', 'Power Adapter', @CatAccesorio, 'ARTICULO', 8.00, 19.00, 15, 5, @UsuarioID, '4005808810214');
END


PRINT '>>> Productos e IMEIs de prueba insertados correctamente. <<<';
GO

