-- ============================================================
-- MIGRACIÓN: ES_TELEFONO (BIT) -> TIPO_PRODUCTO (VARCHAR(20))
-- ============================================================
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE InnovaTecBD;
GO

-- 1. Eliminar vista que depende de ES_TELEFONO
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'V_STOCK_CRITICO' AND schema_id = SCHEMA_ID('INV'))
    DROP VIEW INV.V_STOCK_CRITICO;
GO

-- 2. Agregar nueva columna (si no existe aún)
IF COL_LENGTH('INV.PRODUCTOS', 'TIPO_PRODUCTO') IS NULL
    ALTER TABLE INV.PRODUCTOS ADD TIPO_PRODUCTO VARCHAR(20) NULL;
GO

-- 3. Migrar datos existentes (Lógica mejorada para 3 tipos)
IF COL_LENGTH('INV.PRODUCTOS', 'ES_TELEFONO') IS NOT NULL
BEGIN
    UPDATE P
    SET TIPO_PRODUCTO = 
        CASE 
            WHEN P.ES_TELEFONO = 1 THEN 'TELEFONO'
            WHEN C.NOMBRE LIKE '%Accesorio%' THEN 'ACCESORIO'
            ELSE 'ARTICULO'
        END
    FROM INV.PRODUCTOS P
    LEFT JOIN INV.CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE P.TIPO_PRODUCTO IS NULL;
END
GO

-- 4. Aplicar NOT NULL
ALTER TABLE INV.PRODUCTOS ALTER COLUMN TIPO_PRODUCTO VARCHAR(20) NOT NULL;
GO

-- 5. Agregar DEFAULT y CHECK (si no existen)
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_TIPO_PRODUCTO')
    ALTER TABLE INV.PRODUCTOS ADD CONSTRAINT DF_TIPO_PRODUCTO DEFAULT 'ARTICULO' FOR TIPO_PRODUCTO;
GO

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CHK_TIPO_PRODUCTO')
    ALTER TABLE INV.PRODUCTOS ADD CONSTRAINT CHK_TIPO_PRODUCTO CHECK (TIPO_PRODUCTO IN ('TELEFONO','ARTICULO','ACCESORIO'));
GO

-- 6. Eliminar DEFAULT constraint viejo de ES_TELEFONO
IF COL_LENGTH('INV.PRODUCTOS', 'ES_TELEFONO') IS NOT NULL
BEGIN
    DECLARE @ConstraintName NVARCHAR(200);
    SELECT @ConstraintName = dc.name
    FROM sys.default_constraints dc
    JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
    WHERE dc.parent_object_id = OBJECT_ID('INV.PRODUCTOS') AND c.name = 'ES_TELEFONO';
    
    IF @ConstraintName IS NOT NULL
        EXEC('ALTER TABLE INV.PRODUCTOS DROP CONSTRAINT [' + @ConstraintName + ']');
    
    -- Ahora sí, eliminar la columna
    ALTER TABLE INV.PRODUCTOS DROP COLUMN ES_TELEFONO;
    PRINT '>>> Columna ES_TELEFONO eliminada correctamente. <<<';
END
GO

-- 7. Recrear vista V_STOCK_CRITICO
CREATE VIEW INV.V_STOCK_CRITICO AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE,
    P.MARCA,
    P.MODELO,
    P.STOCK_ACTUAL,
    P.STOCK_MINIMO,
    P.ESTADO_STOCK,
    P.TIPO_PRODUCTO,
    (SELECT COUNT(1) FROM INV.EQUIPOS_IMEI I
     WHERE I.ID_PRODUCTO = P.ID_PRODUCTO AND I.ESTADO_IMEI = 'DISPONIBLE') AS IMEI_DISPONIBLES
FROM INV.PRODUCTOS P
WHERE P.ACTIVO = 1
  AND P.ESTADO_STOCK IN ('CRITICO','AGOTADO');
GO

PRINT '>>> Migración ES_TELEFONO -> TIPO_PRODUCTO completada exitosamente. <<<';
GO
