USE InnovaTecBD;
GO

-- Add the missing module if it doesn't exist
IF NOT EXISTS (SELECT 1 FROM CAT.MODULOS WHERE NOMBRE = 'Etiquetas')
BEGIN
    INSERT INTO CAT.MODULOS (NOMBRE, ICONO, CONTROLLER, ORDEN) VALUES ('Etiquetas', 'fa-barcode', 'Etiquetas', 7);
END

-- Assign the new module to ALL existing administrators
DECLARE @IdModulo INT = (SELECT ID_MODULO FROM CAT.MODULOS WHERE NOMBRE = 'Etiquetas');

INSERT INTO ADM.USUARIO_MODULOS (ID_USUARIO, ID_MODULO)
SELECT U.ID_USUARIO, @IdModulo 
FROM ADM.USUARIOS U
JOIN CAT.ROLES R ON U.ID_ROL = R.ID_ROL
WHERE R.NOMBRE = 'ADMINISTRADOR'
  AND NOT EXISTS (
      SELECT 1 FROM ADM.USUARIO_MODULOS UM 
      WHERE UM.ID_USUARIO = U.ID_USUARIO AND UM.ID_MODULO = @IdModulo
  );
GO
